# Generated by Django 6.0.5 on 2026-05-25 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField(unique=True)),
                ('numero_contrato', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.BigIntegerField()),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'verbose_name': 'Titular',
                'verbose_name_plural': 'Titulares',
                'db_table': 'Titular',
            },
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('cedula', models.BigIntegerField(unique=True)),
                ('parentesco', models.CharField(max_length=100)),
                ('edad_afiliacion', models.PositiveSmallIntegerField()),
                ('edad_actual', models.PositiveSmallIntegerField()),
                ('fecha_afiliacion', models.DateField()),
                ('mascota', models.BooleanField(default=False)),
                ('tipo_mascota', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios', to='client.titular')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'Beneficiario',
            },
        ),
    ]
