# Generated by Django 6.0.5 on 2026-06-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titular',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True),
        ),
    ]
