# Generated by Django 6.0.5 on 2026-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_titular_fecha_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='raza',
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='edad_afiliacion',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
