# Generated by Django 6.0.5 on 2026-06-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_mascota_edad_remove_mascota_identificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='cobro_edad_aplicado',
            field=models.BooleanField(default=False),
        ),
    ]
