# Generated by Django 6.0.5 on 2026-07-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_beneficiario_cobro_edad_aplicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
    ]
