# Generated by Django 6.0.5 on 2026-07-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
