# Generated by Django 6.0.5 on 2026-06-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ultimo_pago', models.DateTimeField(auto_now_add=True)),
                ('plan_vencido', models.BooleanField(default=False)),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.titular')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
            },
        ),
    ]
