# Generated by Django 6.0.5 on 2026-06-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='monto',
            new_name='monto_mensual_tarifa',
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_cargos_unicos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=24000.0, max_digits=10),
            preserve_default=False,
        ),
    ]
