# Generated by Django 6.0.5 on 2026-07-05 18:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_beneficiario_cobro_edad_aplicado'),
        ('payment', '0002_rename_monto_pago_monto_mensual_tarifa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('periodo_anio', models.PositiveSmallIntegerField()),
                ('periodo_mes', models.PositiveSmallIntegerField()),
                ('monto_mensual_tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_cargos_unicos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('anulada', 'Anulada')], default='generada', max_length=20)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='payment.pago')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='client.titular')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Factura',
                'ordering': ['-fecha_emision'],
                'constraints': [models.UniqueConstraint(fields=('pago', 'periodo_anio', 'periodo_mes'), name='factura_unica_por_pago_y_periodo')],
            },
        ),
    ]
