# Generated by Django 6.0.5 on 2026-07-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='proximo_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Proximo Pago'),
        ),
    ]
