# Generated by Django 6.0.5 on 2026-07-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_pago_proximo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_mascotas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_beneficiario_extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_cobro_edad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
