# Generated by Django 6.0.5 on 2026-07-20 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelTable(
            name='plan',
            table='Plan',
        ),
    ]
