# Generated by Django 6.0.5 on 2026-07-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_plan_options_alter_plan_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='edad_maxima',
            field=models.PositiveIntegerField(default=65, verbose_name='Edad Máxima'),
        ),
    ]
